[package]
name = "home-finance-api"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
dotenv = "0.15.0"
mongodb = "3.1.0"
serde = "1.0.210"
serde_json = "1.0.128"
tokio = "1.40.0"
