[package]
name = "home-finance-api"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
argon2 = "0.5.3"
dotenv = "0.15.0"
jsonwebtoken = "9.3.0"
mongodb = { version = "3.1.0", features = ["sync"] }
once_cell = "1.19.0"
serde = "1.0.210"
serde_json = "1.0.128"
tokio = "1.40.0"
